### ISSUE TITLE
Support more storage solutions

### ISSUE THREAD

**Issue by mikberg** [cognitedata/bazel-snapshots#8]
We are currently integrated with gcs storage buckets as a storage solution. Ideally, we should support arbitrary solutions of getting the snapshots. This would hopefully also allow us to remove a whole lot of go dependencies.

**Comment by kondanta** [comment]
I think we can use REST API for the GCS, which, I assume, allows us to reduce the number of dependencies and let us support any storages that can be accessed via REST API like AWS: S3.

What are your thoughts on this?
